import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, basename, join, resolve } from 'node:path';
import { HotelCatalogParser } from './hotel-catalog.parser';
import { HotelCatalogNormalizer } from './hotel-catalog.normalizer';
import { HotelCatalogValidator } from './hotel-catalog.validator';
import { HotelCatalogDeduplicator } from './hotel-catalog.deduplicator';
import {
  CleanHotel,
  DuplicateCandidate,
  NormalizedHotel,
  PipelineStats,
  RejectedHotel,
} from './hotel-catalog.types';
import {
  HOTEL_CATALOG_FILE,
  HotelCatalogRecord,
  validateHotelCatalogRecord,
} from '../../modules/hotels/catalog/hotel-catalog-record';

/**
 * Hotel-catalog data pipeline (offline data-prep — no database).
 *
 *   Raw .docx -> Parse -> Normalize -> Validate -> Deduplicate -> Clean JSON + Report
 *
 * The cleaned JSON it emits (assets/generated/hotels.cleaned.json) is the single
 * source of truth the Mongo seeder consumes. Run it with:
 *
 *   npm run hotels:build          (uses the default asset in backend/assets)
 *   npm run hotels:build -- <path-to.docx> <output-dir>
 */

const BACKEND_ROOT = resolve(__dirname, '../../..');
const DEFAULT_ASSET = join(BACKEND_ROOT, 'assets', 'hotel list 3, 4 & 5 star.docx');
const DEFAULT_REPORT = join(BACKEND_ROOT, 'HOTEL_DATA_REPORT.md');

/** Project the seed-ready records onto the file-based HotelCatalogRecord contract. */
function toCatalogRecords(clean: CleanHotel[]): HotelCatalogRecord[] {
  return clean.map((h) => ({
    name: h.name,
    city: h.city,
    country: h.country,
    rating: h.starRating,
    ...(h.area ? { address: h.area } : {}),
  }));
}

export interface PipelineOutput {
  clean: CleanHotel[];
  stats: PipelineStats;
  candidates: DuplicateCandidate[];
  rejected: RejectedHotel[];
  warnings: string[];
  appliedRules: string[];
}

/** Run the full pipeline in-memory and return everything needed to seed + report. */
export function runHotelPipeline(assetPath = DEFAULT_ASSET): PipelineOutput {
  const parser = new HotelCatalogParser();
  const normalizer = new HotelCatalogNormalizer();
  const validator = new HotelCatalogValidator();
  const deduplicator = new HotelCatalogDeduplicator();

  const raw = parser.parseFile(assetPath);
  const normalized = normalizer.normalizeAll(raw);
  const { valid, rejected, warnings } = validator.validate(normalized);
  const { unique, candidates } = deduplicator.dedupe(valid);

  const clean = toCleanSorted(unique);

  const byRating: Record<string, number> = {};
  for (const h of clean) {
    const k = `${h.starRating}-star`;
    byRating[k] = (byRating[k] ?? 0) + 1;
  }

  const stats: PipelineStats = {
    sourceFile: basename(assetPath),
    sectionsDetected: parser.sections,
    totalRowsScanned: parser.totalRowsScanned,
    headerRowsSkipped: parser.headerRowsSkipped,
    totalRecordsParsed: raw.length,
    validRecords: valid.length,
    rejectedRecords: rejected.length,
    exactDuplicates: candidates.filter((c) => c.kind === 'EXACT_DUPLICATE').length,
    ratingConflicts: candidates.filter((c) => c.kind === 'RATING_CONFLICT').length,
    nearDuplicateCandidates: candidates.filter((c) => c.kind === 'NEAR_DUPLICATE').length,
    missingAreaRecords: clean.filter((h) => !h.area).length,
    finalSeedCount: clean.length,
    byRating,
  };

  return {
    clean,
    stats,
    candidates,
    rejected,
    warnings,
    appliedRules: [...normalizer.appliedRules].sort(),
  };
}

/** Strip provenance, drop undefined area, and sort for deterministic output. */
function toCleanSorted(records: NormalizedHotel[]): CleanHotel[] {
  return records
    .map((r): CleanHotel => {
      const base: CleanHotel = {
        name: r.name,
        category: r.category,
        starRating: r.starRating as 3 | 4 | 5,
        city: r.city,
        country: r.country,
        isActive: r.isActive,
      };
      if (r.area) base.area = r.area;
      return base;
    })
    .sort((a, b) => b.starRating - a.starRating || a.name.localeCompare(b.name));
}

function buildReport(out: PipelineOutput): string {
  const { stats, candidates, rejected, warnings, appliedRules } = out;
  const conflicts = candidates.filter((c) => c.kind === 'RATING_CONFLICT');
  const exact = candidates.filter((c) => c.kind === 'EXACT_DUPLICATE');
  const near = candidates.filter((c) => c.kind === 'NEAR_DUPLICATE');
  const missingArea = out.clean.filter((h) => !h.area);

  const lines: string[] = [];
  lines.push('# Hotel Catalog — Data Quality Report');
  lines.push('');
  lines.push(`> Source asset: \`assets/${stats.sourceFile}\``);
  lines.push('> Pipeline: Parse → Normalize → Validate → Deduplicate → Clean JSON');
  lines.push('> Generated by `npm run hotels:build` (offline; no database writes).');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Count |');
  lines.push('|--------|------:|');
  lines.push(`| Sections detected | ${stats.sectionsDetected.length} |`);
  lines.push(`| Rows scanned | ${stats.totalRowsScanned} |`);
  lines.push(`| Header rows skipped | ${stats.headerRowsSkipped} |`);
  lines.push(`| **Total records found (parsed)** | **${stats.totalRecordsParsed}** |`);
  lines.push(`| Valid records | ${stats.validRecords} |`);
  lines.push(`| Rejected records | ${stats.rejectedRecords} |`);
  lines.push(`| Exact duplicates removed | ${stats.exactDuplicates} |`);
  lines.push(`| Rating conflicts (flagged) | ${stats.ratingConflicts} |`);
  lines.push(`| Near-duplicate candidates (flagged) | ${stats.nearDuplicateCandidates} |`);
  lines.push(`| Missing-area records | ${stats.missingAreaRecords} |`);
  lines.push(`| **Final seed count** | **${stats.finalSeedCount}** |`);
  lines.push('');
  lines.push('### Final seed count by rating');
  lines.push('');
  lines.push('| Rating | Count |');
  lines.push('|--------|------:|');
  for (const k of Object.keys(stats.byRating).sort().reverse()) {
    lines.push(`| ${k} | ${stats.byRating[k]} |`);
  }
  lines.push('');

  lines.push('## Sections detected');
  lines.push('');
  for (const s of stats.sectionsDetected) lines.push(`- ${s}`);
  lines.push('');

  lines.push('## Normalization rules applied');
  lines.push('');
  if (appliedRules.length === 0) lines.push('_None triggered._');
  for (const r of appliedRules) lines.push(`- ${r}`);
  lines.push('');

  lines.push('## Rejected records');
  lines.push('');
  if (rejected.length === 0) {
    lines.push('_None — every parsed record met the minimum contract (name + valid rating)._');
  } else {
    lines.push('| Reason | Record |');
    lines.push('|--------|--------|');
    for (const r of rejected) {
      const name = 'name' in r.record ? r.record.name : r.record.rawName;
      lines.push(`| ${r.reason} | ${name || '(empty)'} |`);
    }
  }
  lines.push('');

  lines.push('## Rating conflicts (require business review)');
  lines.push('');
  if (conflicts.length === 0) {
    lines.push('_None._');
  } else {
    for (const c of conflicts) lines.push(`- ⚠️ ${c.note}`);
  }
  lines.push('');

  lines.push('## Exact duplicates removed');
  lines.push('');
  if (exact.length === 0) {
    lines.push('_None._');
  } else {
    for (const c of exact) {
      lines.push(`- "${c.dropped?.name}" (row ${c.dropped?.sourceRow}) — ${c.note}`);
    }
  }
  lines.push('');

  lines.push('## Near-duplicate candidates (both kept — review, do not blind-merge)');
  lines.push('');
  if (near.length === 0) {
    lines.push('_None above the similarity threshold._');
  } else {
    for (const c of near) {
      lines.push(`- "${c.kept.name}" vs "${c.other?.name}" (similarity ${c.similarity})`);
    }
  }
  lines.push('');

  lines.push('## Missing-area records (kept; area is optional)');
  lines.push('');
  if (missingArea.length === 0) {
    lines.push('_None — every record has an area._');
  } else {
    for (const h of missingArea) lines.push(`- ${h.name} (${h.starRating}-star)`);
  }
  lines.push('');

  if (warnings.length > 0) {
    lines.push('## Warnings');
    lines.push('');
    for (const w of warnings) lines.push(`- ${w}`);
    lines.push('');
  }

  lines.push('## Sample of cleaned records (first 20)');
  lines.push('');
  lines.push('```json');
  lines.push(JSON.stringify(out.clean.slice(0, 20), null, 2));
  lines.push('```');
  lines.push('');
  return lines.join('\n');
}

function main(): void {
  const [, , assetArg, outFileArg] = process.argv;
  const assetPath = assetArg ? resolve(assetArg) : DEFAULT_ASSET;
  const catalogPath = outFileArg ? resolve(outFileArg) : HOTEL_CATALOG_FILE;

  const out = runHotelPipeline(assetPath);
  const records = toCatalogRecords(out.clean);

  // Build-time validation: every emitted record MUST satisfy the file contract.
  // A single invalid row fails the build rather than shipping a broken catalog.
  const invalid = records
    .map((record, index) => ({ index, ...validateHotelCatalogRecord(record) }))
    .filter((r) => !r.valid);
  if (invalid.length > 0) {
    console.error(`\n✗ Dataset validation failed — ${invalid.length} invalid record(s):`);
    for (const r of invalid.slice(0, 20)) {
      console.error(`  - record #${r.index}: ${r.reason}`);
    }
    process.exit(1);
  }

  mkdirSync(dirname(catalogPath), { recursive: true });
  writeFileSync(catalogPath, `${JSON.stringify(records, null, 2)}\n`, 'utf8');
  writeFileSync(DEFAULT_REPORT, buildReport(out), 'utf8');

  // Console summary + a 20-record sample for quick human review.
   
  console.log('\n=== Hotel Catalog Pipeline ===');
  console.log(`Source          : assets/${out.stats.sourceFile}`);
  console.log(`Parsed          : ${out.stats.totalRecordsParsed}`);
  console.log(`Valid           : ${out.stats.validRecords}`);
  console.log(`Rejected        : ${out.stats.rejectedRecords}`);
  console.log(
    `Duplicates      : ${out.stats.exactDuplicates} exact, ` +
      `${out.stats.ratingConflicts} rating-conflict, ` +
      `${out.stats.nearDuplicateCandidates} near`,
  );
  console.log(`Missing area    : ${out.stats.missingAreaRecords}`);
  console.log(`By rating       : ${JSON.stringify(out.stats.byRating)}`);
  console.log(`FINAL SEED COUNT: ${out.stats.finalSeedCount}`);
  console.log(`Validated       : ${records.length} record(s) against HotelCatalogRecord`);
  console.log(`\nWrote: ${catalogPath}`);
  console.log(`Wrote: ${DEFAULT_REPORT}`);
  console.log('\n--- Sample of 20 cleaned records ---');
  console.table(
    out.clean.slice(0, 20).map((h) => ({
      name: h.name,
      star: h.starRating,
      area: h.area ?? '(none)',
      city: h.city,
    })),
  );
   
}

if (require.main === module) {
  main();
}
